name: Deploy uni-fastkit site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # 步骤2：修改代码
      - name: Modify the code
        run: |
          sed -i 's|VITE_APP_BASE= '/'|VITE_APP_BASE= '/uni-faskit/'|g' .env
          echo "修改后的.env内容:"
          cat .env | grep VITE_APP_BASE  # 只打印包含VITE_APP_BASE的行

      # 安装 pnpm
      - uses: pnpm/action-setup@v4.2.0
        name: Setup pnpm
        with:
          version: 10
          run_install: false

      # 设置 Node.js 20 版本
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: "20"
          cache: 'pnpm'

      # 安装项目依赖（使用 pnpm）
      - name: Install dependencies
        run: pnpm install

      # 运行打包命令（使用 pnpm 执行脚本）
      - name: Build H5
        run: pnpm run build:h5
  
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./dist/build/h5

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5
